services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\MultisiteBelogin\:
    resource: '../Classes/*'


  WapplerSystems\MultisiteBelogin\Service\TokenGenerator:
    public: true

  WapplerSystems\MultisiteBelogin\Service\Validation:
    public: true

  WapplerSystems\MultisiteBelogin\Controller\TokenController:
    public: true

  WapplerSystems\MultisiteBelogin\EventListener\BeforeUserLogoutEventListener:
    tags:
      - name: event.listener
        identifier: 'multisiteBelogin-eventListener'
        event: TYPO3\CMS\Core\Authentication\Event\BeforeUserLogoutEvent
